language: node_js
node_js:
- '4.2'
branches:
  only:
  - master
  - staging
before_install:
- npm install
install:
- npm run generate
deploy:
  - provider: s3
    on:
      branch: master
    bucket: computerlab.io
    region: us-west-2
    skip_cleanup: true
    local_dir: public
    secret_access_key:
      secure: SF0EvPJUwG/cIkcTbzo3cfY4uD4q2QJrSQGNKdlslorw/DrAmGthmhC+YAeDsNx4vrk0MCfk6i6zM6yKna2fxCAe6IsyzqKcKmgW1qaXZW/gMeqCBQIQU2ePHb9EQnBvuuo1Tl0o2bBTQLqnJDXdxamwQs4/LMQzvgA3yIimmFo8n4GUGYVDqVstDvCHuNPYoRkqU05AE1PXyIETLc8PwA/6D12i8dyA/nD9j2zkHttrYzIZqriX1znop+OPN4rWUwRZULPpLSgnuwt/MdgHolUSvsZMRY10DYgrxia7cjrd21fkUltBfiHSA5ruq6FwQVeLfc7SKbadPpu/NLXdsVE1lt5EIkZhAiRrzT9sCbW7m1tMp2yvmjve9FaVGAjoBIFMS7X08HPZMDTPsS3vA/du3CHbSWyTERhN7oYLf/s6jyW5vSM8nf/F/kObGJ2JrmVueqe5WM1Hwf8TsHdPRvIoxxCJ2ApL6YY8awv0a7aXT7P5vtU/0hwQvpZ+SlCJ8nThYz6r4WHN8bS7ISsAumwK/b5wnCCr4LOhhvaoIrgcOFy07YfJjWyN0uRwYwT3oKbYHgo1HjektvXbTg/AOtCp8+WhJx+ksEcX5iNllxNPC2mJTyXEZic8wsdHms/A9pIf3jv+8M6tTaqNe4Taj7o9+1ZPhKy0bJUA0BuU94I=
    access_key_id:
      secure: QqPBneYB69N2HZyyFq0Av01cVyGJ9QY2LPnwWSppfI4J3FDciHh3X4+z2LpEPWH2TcHmELltHNi5EkNEyEBhimku61SiE8E7ByjpQZpduXLlwvK7GHiBylSAtbbLhit5A4WkY0vWC1gq1JTNi8P2QeFeqCfnx64IKPCsKWxdbu7CUrp2OUnjLbsEHoUDfkkQS7Hcw0CmFqyEKfS7wHzYxdyE4Mnjw0fbjn9zYY2nnCOZa1evRp4dlZo3CfMdVVwe3UqFHhxiVt2vVBI/HO3gHWX7ImBPFz9Odjayx28cyqek1QHN8sZ70mwSkmws0muLl23JdGgh+j8DWXWbpgVOvn1pYt+2sIizG1TwsxuOFm4KK02pBRL04YcJjyNUyoUtswjy+FovttdxPVaLyU3AIP/RWeKgPfui5Fuo3D4p9pTxIi+cQ8dZvvGJI4h319dJQQN0H5W4l5pf5+jN2kkEG+a/ewhLRVv2KIGXwk7oTW6QJf/rdBPhDoM/b2CvYSEu1s/DOC5qwx+hoS21SopK1Hu3NBtrv8YNRXCl/8lNPWrmtTP7H2odPtfai7Y4I97VSe5tMOdLahQvUz0AzUqJw4gg1klUvBXh2+PmeiRouwddqDCBRQoyFqETANqVz/xjIAzAj248BToxilXoHqo65Y3vzPlCGRuUysVuOPzOmus=
  - provider: s3
    on:
      branch: staging
    bucket: staging.computerlab.io
    region: us-west-2
    skip_cleanup: true
    local_dir: public
    secret_access_key:
      secure: SF0EvPJUwG/cIkcTbzo3cfY4uD4q2QJrSQGNKdlslorw/DrAmGthmhC+YAeDsNx4vrk0MCfk6i6zM6yKna2fxCAe6IsyzqKcKmgW1qaXZW/gMeqCBQIQU2ePHb9EQnBvuuo1Tl0o2bBTQLqnJDXdxamwQs4/LMQzvgA3yIimmFo8n4GUGYVDqVstDvCHuNPYoRkqU05AE1PXyIETLc8PwA/6D12i8dyA/nD9j2zkHttrYzIZqriX1znop+OPN4rWUwRZULPpLSgnuwt/MdgHolUSvsZMRY10DYgrxia7cjrd21fkUltBfiHSA5ruq6FwQVeLfc7SKbadPpu/NLXdsVE1lt5EIkZhAiRrzT9sCbW7m1tMp2yvmjve9FaVGAjoBIFMS7X08HPZMDTPsS3vA/du3CHbSWyTERhN7oYLf/s6jyW5vSM8nf/F/kObGJ2JrmVueqe5WM1Hwf8TsHdPRvIoxxCJ2ApL6YY8awv0a7aXT7P5vtU/0hwQvpZ+SlCJ8nThYz6r4WHN8bS7ISsAumwK/b5wnCCr4LOhhvaoIrgcOFy07YfJjWyN0uRwYwT3oKbYHgo1HjektvXbTg/AOtCp8+WhJx+ksEcX5iNllxNPC2mJTyXEZic8wsdHms/A9pIf3jv+8M6tTaqNe4Taj7o9+1ZPhKy0bJUA0BuU94I=
    access_key_id:
      secure: QqPBneYB69N2HZyyFq0Av01cVyGJ9QY2LPnwWSppfI4J3FDciHh3X4+z2LpEPWH2TcHmELltHNi5EkNEyEBhimku61SiE8E7ByjpQZpduXLlwvK7GHiBylSAtbbLhit5A4WkY0vWC1gq1JTNi8P2QeFeqCfnx64IKPCsKWxdbu7CUrp2OUnjLbsEHoUDfkkQS7Hcw0CmFqyEKfS7wHzYxdyE4Mnjw0fbjn9zYY2nnCOZa1evRp4dlZo3CfMdVVwe3UqFHhxiVt2vVBI/HO3gHWX7ImBPFz9Odjayx28cyqek1QHN8sZ70mwSkmws0muLl23JdGgh+j8DWXWbpgVOvn1pYt+2sIizG1TwsxuOFm4KK02pBRL04YcJjyNUyoUtswjy+FovttdxPVaLyU3AIP/RWeKgPfui5Fuo3D4p9pTxIi+cQ8dZvvGJI4h319dJQQN0H5W4l5pf5+jN2kkEG+a/ewhLRVv2KIGXwk7oTW6QJf/rdBPhDoM/b2CvYSEu1s/DOC5qwx+hoS21SopK1Hu3NBtrv8YNRXCl/8lNPWrmtTP7H2odPtfai7Y4I97VSe5tMOdLahQvUz0AzUqJw4gg1klUvBXh2+PmeiRouwddqDCBRQoyFqETANqVz/xjIAzAj248BToxilXoHqo65Y3vzPlCGRuUysVuOPzOmus=
notifications:
  slack:
    rooms:
    - computer-lab:9vWrWatbwuLTfTfb37qfeNR8#notifications
